-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `medallion_dev`;
USE SCHEMA `bronze`;

DECLARE catalog_target STRING DEFAULT 'medallion_dev';
DECLARE schema_target STRING DEFAULT 'bronze';

-- COMMAND ----------

-- Datos sin procesar (raw)
SELECT * FROM json.`/Volumes/main/dbdemos_retail_c360/c360/users` LIMIT 5;
SELECT * FROM csv.`/Volumes/main/dbdemos_retail_c360/c360/events` LIMIT 5;
SELECT * FROM json.`/Volumes/main/dbdemos_retail_c360/c360/orders` LIMIT 5;

-- COMMAND ----------

-- DBTITLE 1,Cell 3
SELECT * 
FROM IDENTIFIER(catalog_target || '.' || schema_target || '.churn_event_bronze') 
LIMIT 10;
