# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `medallion_dev`")
spark.sql("USE SCHEMA `bronze`")

catalog_target = "medallion_dev"
bronze_schema_target = "bronze"

# COMMAND ----------

# Datos sin procesar (raw)
df = spark.read.format("json").load("/Volumes/main/dbdemos_retail_c360/c360/users")
display(df.limit(5))

df = spark.read.format("csv").option("header", True).load("/Volumes/main/dbdemos_retail_c360/c360/events")
display(df.limit(5))

df = spark.read.format("json").load("/Volumes/main/dbdemos_retail_c360/c360/orders")
display(df.limit(5))

# COMMAND ----------

# Datos bronze
display(spark.sql(f"SELECT * FROM {catalog_target}.{bronze_schema_target}.churn_event_bronze LIMIT 10"))
display(spark.sql(f"SELECT * FROM {catalog_target}.{bronze_schema_target}.churn_user_bronze LIMIT 10"))
display(spark.sql(f"SELECT * FROM {catalog_target}.{bronze_schema_target}.churn_order_bronze LIMIT 10"))

# COMMAND ----------

# Datos Silver
